Repository hardlyhuman/TFExplorer, pull requests merged in 2020-05, with the labels that each got.

#9 Fix issue 3
  README.md
Labels: await_review

#10 Add User model and token based authentication
  .travis.yml
  TFExplorer/settings.py
  TFExplorer/urls.py
  black.toml
  registration/__init__.py
  registration/admin.py
  registration/apps.py
  registration/migrations/0001_initial.py
  registration/migrations/__init__.py
  registration/models.py
  registration/tests.py
  registration/urls.py
  registration/views.py
  requirements.txt
Labels: await_rebase

#11 Added BASE API Models
  TFExplorer/settings.py
  base/migrations/0001_initial.py
  base/models.py
Labels: await_on_submitter
